### ISSUE TITLE
ancp-bids 0.0.10 crashes

### ISSUE THREAD

**Issue by lmichalke** [ANCPLabOldenburg/ancp-bids#16]
Trying to load BIDSLayout with ancp-bids 0.0.10 produces the following error:

Traceback (most recent call last):
  File "/data2/lmichalke/github/ANCP/voxelwiseencoding/voxelwiseencoding/test_bids_loader.py", line 173, in <module>
    test_bids_loader()
  File "/data2/lmichalke/github/ANCP/voxelwiseencoding/voxelwiseencoding/test_bids_loader.py", line 8, in test_bids_loader
    layout=bids.BIDSLayout('/data2/azubaidi/ForrestGumpHearingLoss/BIDS_ForrGump/derivatives/fmriprep')
  File "/home/lmichalke/anaconda3/envs/testbids2/lib/python3.9/site-packages/ancpbids/pybids_compat.py", line 10, in __init__
    self.query = XPathQuery(self.dataset, self.sc)
  File "/home/lmichalke/anaconda3/envs/testbids2/lib/python3.9/site-packages/ancpbids/query.py", line 21, in __init__
    super(XPathQuery, self).__init__(dataset, scm)
  File "/home/lmichalke/anaconda3/envs/testbids2/lib/python3.9/site-packages/ancpbids/query.py", line 13, in __init__
    self.root = dataset.to_etree(mapping_=self.id2x, reverse_mapping_=self.x2id, nsmap_=schema.NS_MAP)
  File "/home/lmichalke/anaconda3/envs/testbids2/lib/python3.9/site-packages/ancpbids/model.py", line 4754, in to_etree
    dataset_description_.to_etree(element, name_='dataset_description', mapping_=mapping_, reverse_mapping_=reverse_mapping_, nsmap_=nsmap_)
  File "/home/lmichalke/anaconda3/envs/testbids2/lib/python3.9/site-packages/ancpbids/model.py", line 4221, in to_etree
    GeneratedBy_.to_etree(element, name_='GeneratedBy', mapping_=mapping_, reverse_mapping_=reverse_mapping_, nsmap_=nsmap_)
AttributeError: 'dict' object has no attribute 'to_etree'

**Comment by erdalkaraca** [comment]
Thanks for reporting,  @lmichalke !
Fixed in 0.0.11

FYI: the implementation had not yet processed complex JSON objects, i.e., in your case, derivatives have a complex structure GeneratedBy which was not read from its JSON representation

**Comment by erdalkaraca** [comment]
Sorry, had to fix one more issue. Please upgrade to 0.0.12.
