### ISSUE TITLE
BIDSLayout.get_metadata() crashes when no parameters/filters provided

### ISSUE THREAD

**Issue by erdalkaraca** [ANCPLabOldenburg/ancp-bids#27]
When calling BIDSLayout.get_metadata() without any fitlers provided, it will throw an exception:

```
Error
Traceback (most recent call last):
  File "C:\work\git-repos\ancp-bids\tests\tests_auto_query.py", line 88, in test_bidslayout_get_metadata
    layout.get_metadata()
  File "C:\work\git-repos\ancp-bids\ancpbids\pybids_compat.py", line 56, in get_metadata
    qry_result = self.get(return_type='lxml', element_source='metadatafiles', *args, **kwargs)
  File "C:\work\git-repos\ancp-bids\ancpbids\pybids_compat.py", line 158, in get
    artifacts = self._query(expr_final, return_lxml_objects=return_type == 'lxml')
  File "C:\work\git-repos\ancp-bids\ancpbids\pybids_compat.py", line 27, in _query
    return self.query.execute(expr, search_node, return_lxml_objects)
  File "C:\work\git-repos\ancp-bids\ancpbids\plugins\plugin_query.py", line 137, in execute
    result = context.xpath(expr)
  File "src\lxml\etree.pyx", line 1597, in lxml.etree._Element.xpath
  File "src\lxml\xpath.pxi", line 305, in lxml.etree.XPathElementEvaluator.__call__
  File "src\lxml\xpath.pxi", line 225, in lxml.etree._XPathEvaluatorBase._handle_result
lxml.etree.XPathEvalError: Invalid expression
```

**Comment by erdalkaraca** [comment]
Fixed and added regression test at

tests.tests_auto_regressions.RegressionsTestCase.test_get_metadata_no_params

Note: calling get_metadata() without params returns a dict object of all available metadata
