### ISSUE TITLE
validation module report.has_errors()

### ISSUE THREAD

**Issue by ancpJR** [ANCPLabOldenburg/ancp-bids#31]
The function call throws an error although errors are in the report:

>>> report.has_errors()
Traceback (most recent call last):
  File ".../IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-95634a3c0769>", line 1, in <module>
    report.has_errors()
  File "./ancp-bids-docu/ancpbids/plugin.py", line 49, in has_errors
    return len(filter(lambda m: m['severity'] == 'error'), self.messages) > 0
TypeError: filter expected 2 arguments, got 1

**Comment by erdalkaraca** [comment]
Fixed the report.has_errors() function: implementation was not properly tested
